"""empty message

Revision ID: bddb165c68a4
Revises: 
Create Date: 2019-10-18 16:40:07.637288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddb165c68a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('displayName', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('job_title', sa.String(length=24), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('soulFood', sa.String(length=1), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('photo_url', sa.String(length=256), nullable=True),
    sa.Column('isNotification', sa.Boolean(), nullable=True),
    sa.Column('isCamera', sa.Boolean(), nullable=True),
    sa.Column('isAlbum', sa.Boolean(), nullable=True),
    sa.Column('createTime', sa.String(length=20), nullable=True),
    sa.Column('lastSignInTime', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
