### 
@domain = http://localhost:3000/v1/
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTE5MCwiaWF0IjoxNTY1MjU4Mzg4fQ.tMjE8nIG-4Cbj3M4OKa6IgExzZ9sZPAmhDSxYHhqC-I

### Login
POST http://localhost:3000/v1/login
Content-Type: {{contentType}}

{
  "phone_number": "0987654321",
  "password": "a12345678"
}

### Create Userr
POST http://localhost:3000/v1/users/created
Content-Type: {{contentType}}

{
  "email": "tomas@aaa.bbb",
  "password": "a12345678",
  "phone_number": "0987654321",
  "display_name": "tomas",
  "gender": "F",
  "job_title": "job title",
  "soul_food": "rice",
  "info": "info",
  "photo_url": "https://cdn.shopifycloud.com/hatchful-web/assets/6fcc76cfd1c59f44d43a485167fb3139.png",
  "is_notification": false,
  "is_camera": false,
  "is_album": false,
  "rate": 5,
  "disabled": false
}
